from evmautomation.workflows.baseworkflow import BaseWorkflow
from evmautomation.workflows.bscworkflow import BscWorkflow
from evmautomation.workflows.dripfaucetworkflow import DripFaucetWorkflow
from evmautomation.workflows.dripgardenworkflow import DripGardenWorkflow
from evmautomation.workflows.trunkstampedeworkflow import TrunkStampedeWorkflow